# Generated by Django 5.2.7 on 2025-11-12 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmailEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('thread_id', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('email_date', models.DateTimeField()),
                ('body_text', models.TextField()),
                ('category', models.CharField(default='unknown', max_length=50)),
                ('subcategory', models.CharField(default='unknown', max_length=50)),
                ('confidence', models.IntegerField(default=0)),
                ('is_transaction', models.BooleanField(default=False)),
                ('is_statement', models.BooleanField(default=False)),
                ('is_notification', models.BooleanField(default=False)),
                ('parsed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parsed_merchant', models.CharField(blank=True, max_length=200, null=True)),
                ('parsed_transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('parsed_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('gmail_labels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-email_date'],
                'indexes': [models.Index(fields=['category', 'subcategory'], name='credit_card_categor_f7fe5f_idx'), models.Index(fields=['is_transaction', 'email_date'], name='credit_card_is_tran_8b6d46_idx'), models.Index(fields=['sender', 'email_date'], name='credit_card_sender_f10fce_idx')],
            },
        ),
    ]
