# Generated by Django 5.2.7 on 2025-11-13 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_alter_gmailemail_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gmailemail',
            name='credit_card_categor_f7fe5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='gmailemail',
            name='credit_card_is_tran_8b6d46_idx',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='gmail_labels',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='is_notification',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='is_statement',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='is_transaction',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='parsed_amount',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='parsed_merchant',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='parsed_payment_method',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='parsed_transaction_type',
        ),
        migrations.RemoveField(
            model_name='gmailemail',
            name='subcategory',
        ),
        migrations.AddIndex(
            model_name='gmailemail',
            index=models.Index(fields=['email_date'], name='credit_card_email_d_83ecc9_idx'),
        ),
    ]
