# Generated by Django 5.2.4 on 2025-07-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSDetails",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sms", models.TextField()),
                ("identified_account_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                ("merchant_name", models.CharField(max_length=255)),
                ("time_stamp", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_type", models.CharField(max_length=100)),
                ("payment_mode", models.CharField(max_length=100)),
                (
                    "transaction_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MerchantDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merchant_id", models.CharField(max_length=100, unique=True)),
                ("main_category", models.CharField(max_length=100)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AADetails",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("narration", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_type", models.CharField(max_length=100)),
                ("payment_mode", models.CharField(max_length=100)),
                (
                    "transaction_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="sms.smsdetails",
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[("correct", "Correct"), ("incorrect", "Incorrect")],
                        default="correct",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
