# Generated by Django 5.2.4 on 2025-08-13 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0002_smsdetails_merchantdetails_aadetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="AAConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_id", models.CharField(max_length=100, unique=True)),
                ("vua", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="PENDING", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AADataSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawAATransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_id", models.CharField(max_length=100, unique=True)),
                ("narration", models.TextField()),
                (
                    "parsed_amount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("parsed_date", models.DateField(null=True)),
                ("parsed_merchant", models.CharField(max_length=100, null=True)),
                ("raw_payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="aadetails",
            name="transaction_id",
        ),
        migrations.DeleteModel(
            name="MerchantDetails",
        ),
        migrations.AddField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="aaconsent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aadatasession",
            name="consent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms.aaconsent"
            ),
        ),
        migrations.AddField(
            model_name="rawaatransaction",
            name="consent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms.aaconsent"
            ),
        ),
        migrations.AddField(
            model_name="rawaatransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="AADetails",
        ),
        migrations.DeleteModel(
            name="SMSDetails",
        ),
    ]
