# Generated by Django 5.2.4 on 2025-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0003_aaconsent_aadatasession_otprequest_rawaatransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawaatransaction",
            name="parsed_received_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawaatransaction",
            name="parsed_transaction_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
