# Generated by Django 5.2.4 on 2025-09-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0004_rawaatransaction_parsed_received_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawaatransaction",
            name="main_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rawaatransaction",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
