# Generated by Django 5.2.4 on 2025-09-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0005_rawaatransaction_main_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawaatransaction",
            old_name="parsed_merchant",
            new_name="parsed_merchant_name",
        ),
        migrations.AddField(
            model_name="rawaatransaction",
            name="parsed_payment_mode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rawaatransaction",
            name="parsed_date",
            field=models.DateTimeField(null=True),
        ),
    ]
