# Generated by Django 5.2.4 on 2025-09-04 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sms",
            "0006_rename_parsed_merchant_rawaatransaction_parsed_merchant_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RawSMSTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_id", models.CharField(max_length=100, unique=True)),
                ("narration", models.TextField()),
                (
                    "parsed_amount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("parsed_date", models.DateTimeField(null=True)),
                ("parsed_merchant_name", models.CharField(max_length=100, null=True)),
                (
                    "parsed_transaction_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "parsed_payment_mode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("parsed_received_content", models.TextField(blank=True, null=True)),
                ("raw_payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "main_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sms.aaconsent"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
