# Generated by Django 5.2.4 on 2025-09-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0007_rawsmstransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawaatransaction",
            name="matched_sms_txn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sms.rawsmstransaction",
            ),
        ),
        migrations.AddField(
            model_name="rawsmstransaction",
            name="matched_aa_txn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sms.rawaatransaction",
            ),
        ),
    ]
