# Generated by Django 5.2.4 on 2025-09-10 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0009_gmailtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gmailtoken",
            name="user",
        ),
    ]
