# Generated by Django 5.2.4 on 2025-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0010_remove_gmailtoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmailtoken",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
