# Generated by Django 5.2.7 on 2025-10-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_smsmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='sms_customuser',
        ),
    ]
