# Generated by Django 5.2.7 on 2025-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
