# Generated by Django 5.2.7 on 2025-11-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_smsmessage_external_id_smsmessage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailemail',
            name='user',
        ),
        migrations.DeleteModel(
            name='GmailToken',
        ),
        migrations.DeleteModel(
            name='GmailEmail',
        ),
    ]
